### ISSUE TITLE
[New Feature] Introducing css module and pipelining

### ISSUE THREAD

**Issue by khaing211** [eriwen/gradle-css-plugin#16]
You already implemented source extension. The next step is to use gradle Rule to create pipeline of combineCss, minifyCss, gzipCss for each source

Example:
    
	css.source {
		dev {
			css {
				srcDir "app/styles"
				include "*.css"
				exclude "*.min.css"
			}
			
			transpileOpt {
				   // your tasks options for combineCss, minifyCss, gzipCss
			}
		}
	}  

When you run this command

	$ ./gradlew transpileDev

More about gradle Rule:
http://chimera.labs.oreilly.com/books/1234000001741/ch03.html#_rules

**Comment by eriwen** [comment]
This is a good suggestion - thank you. The future of this plugin will be very different from today and using gradle Rule won't be applicable.
