### ISSUE TITLE
Example csslint config does not work

### ISSUE THREAD

**Issue by FrontierPsychiatrist** [eriwen/gradle-css-plugin#39]
I tried to apply the plugin to my project but using the csslint task fails.
I'm getting

```
No such property: source for class: com.eriwen.gradle.css.CssLintExtension_Decorated
```

when I configure

```
css.source {
    dev {
        css {
            srcDir "src/main/resources/static/css"
            include "*.css"
            exclude "*.min.css"
        }
    }
}

csslint {
    source = css.source.dev.css.files
    dest = "${buildDir}/csslint.out"
}
```

and run `gradle csslint`.

I'm using Gradle 2.7 on Linux with JDK 1.8.0_60.

**Comment by sauliuxx** [comment]
Try this:
csslint {
    tasks.csslint.source = css.source.dev.css.files
    tasks.csslint.dest = "${buildDir}/csslint.out"
}
