### ISSUE TITLE
Issues with gradle 2.12

### ISSUE THREAD

**Issue by java4africa** [eriwen/gradle-css-plugin#40]
This worked in all versions prior 2.11 and before, but seems that 2.12 breaks something.

Using version:
id "com.eriwen.gradle.css" version "1.11.1"

Could not create an instance of type com.eriwen.gradle.css.source.internal.DefaultCssSourceSet_Decorated.

``
css.source {
    allfiles {
        css {
            srcDir "src/main/webapp/css/stylesheets/"
            include "*.css"
	    exclude "*.min.css"
        }
    }
}
``

**Comment by java4africa** [comment]
Probably related to this change - but not sure how to fix that -
https://github.com/gradle/gradle/commit/4e5e9fba8cb2456b191a1365d786e914b2526a7b#diff-388e39e0ebf12abd06ab056c8d755db0

Caused by: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: org.gradle.api.internal.file.DefaultSourceDirectorySet(java.lang.String, java.lang.String, org.gradle.api.internal.file.BaseDirFileResolver)
	at com.eriwen.gradle.css.source.internal.DefaultCssSourceSet.<init>(DefaultCssSourceSet.groovy:26)

**Comment by protoEvangelion** [comment]
@eriwen, @java4africa was there a resolution for this?

I am running into the same issue:

```
> Could not create an instance of type com.eriwen.gradle.css.source.internal.DefaultCssSourceSet_Decorated.
   > Could not find matching constructor for: org.gradle.api.internal.file.DefaultSourceDirectorySet(java.lang.String, java.lang.String, org.gradle.api.internal.file.BaseDirFileResolver)
```
 Gradle 4.10.2
