### ISSUE TITLE
publish to gragle plugin repo

### ISSUE THREAD

**Issue by java4africa** [eriwen/gradle-css-plugin#41]
https://plugins.gradle.org/plugin/com.eriwen.gradle.css shows that the latest version is 1.11.1
Do the latest versions need to be pushed to gradle plugins?

If they are not on plugins.gralde.org then the "id" format does not work:
```
plugins {
  id "com.eriwen.gradle.css" version "2.12.0"
}
```

But the old/alternate format does work fine:
```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.eriwen:gradle-js-plugin:2.12.0'
        classpath 'com.eriwen:gradle-css-plugin:2.12.0'	
    }
}
```

**Comment by eriwen** [comment]
Sorry about this. I've been struggling with Gradle exceptions here and I'll update here once I get it solved.

**Comment by eriwen** [comment]
Done! https://plugins.gradle.org/plugin/com.eriwen.gradle.css
